Forwardport PR 261 to main (ALOHA 2024: Clean up photometry contents)
astropy/astropy-workshop pull request #264
Opened 2024-11-24 14:52 UTC by pllim

Forwardport #261

Fix #263

2024-11-24 15:54 UTC, mwcraig approved these changes
This looks good to me. I did not check all of the new links but did spot check a couple, which worked.

2024-11-24 21:32 UTC, pllim commented
Is there a way to run link check on all the workshop notebooks going forward? 🤔

2024-11-25 17:26 UTC, larrybradley reviewed
I see that 25.9463 is the 2012 zeropoint, but the change here to 25.936 doesn't agree with the current zeropoint calculated in stsynphot.

I get 25.94471861842982. (25.944).

The other changes are all fine.

2024-11-25 17:34 UTC, pllim commented
> 25.936 doesn't agree with the current zeropoint calculated in stsynphot

The WFC3 site mentioned in notebook (https://www.stsci.edu/hst/instrumentation/wfc3/data-analysis/photometric-calibration/ir-photometric-calibration) said values are from 2020 "for an infinite aperture of radius 6 arcsec". stsynphot follows whatever lookup tables are available at the time (which is probably newer than 2020) and also depends on exact obsmode (see https://stsynphot.readthedocs.io/en/stable/stsynphot/appendixb_inflight.html#wfc3).

2024-11-25 17:37 UTC, pllim commented
If you want the values to be from 2012, then might have to update the URL because I cannot easily find 25.9463 on that page for that filter.

2024-11-25 17:41 UTC, larrybradley commented
Here are the 2012 values:
https://www.stsci.edu/hst/instrumentation/wfc3/data-analysis/photometric-calibration/ir-photometric-calibration/previous-ir-photometric-calibration

I think it's fine to update, but we should probably use the best current value.  I used an obsmode of 'wfc3,ir,f160w' which is also for an "infinite" aperture.  See https://spacetelescope.github.io/hst_notebooks/notebooks/WFC3/zeropoints/zeropoints.html.  It's interesting the that current calibration value is very close to the 2012 value, but the 2020 value has a larger difference.

2024-11-25 17:43 UTC, larrybradley commented
I also tried changing the MJD to the range spanned by the observations, but the zeropoint differences are ~10e-8.

2024-11-25 17:47 UTC, pllim commented
Weird... should we send in help call to WFC3 Team?

As for the notebook, I am not sure how to modify the text to say value is from stsynphot without overcomplicating things (the PYSYN_CDBS stuff is a pain to set up if users want to reproduce it). Should I just revert the zeropoint stuff from this PR?

2024-11-25 18:08 UTC, larrybradley commented
Can you simply say it's the latest zeropoint from `stsynphot` and use the HST notebook URL as a reference?

2024-11-25 19:42 UTC, pllim commented
Sure, I can. Meanwhile, I submitted INC0206518 to HST Help Desk.

2024-11-25 20:17 UTC, pllim commented
@larrybradley , I added a commit to address your zeropoint concerns. FYI.

2025-01-06 18:25 UTC, larrybradley requested changes
The WFC3 team  released new zeropoints (https://www.stsci.edu/hst/instrumentation/wfc3/data-analysis/photometric-calibration/ir-photometric-calibration).

@pllim Please update to the new values:
* For F160W, the ABmag zpt is 25.941.
* For F105W, the ABmag zpt is 26.266.

2025-01-06 18:35 UTC, pllim reviewed
@larrybradley , like this? Anything else?

2025-01-06 18:35 UTC, pllim commented on 09-Photutils/01-aperture_basics.ipynb
> +    "f160w_zpt = 25.9447  # HST/WFC3 F160W ABmag zero point for flux in e-/s\n",
```suggestion
    "f160w_zpt = 25.941  # HST/WFC3 F160W ABmag zero point for flux in e-/s\n",
```

2025-01-06 18:35 UTC, pllim commented on 09-Photutils/01-aperture_basics.ipynb
> +    "* The HST/WFC3 F160W ABmag zero point for data in units of e-/s is `25.9447`."
```suggestion
    "* The HST/WFC3 F160W ABmag zero point for data in units of e-/s is `25.941`."
```

2025-01-06 18:35 UTC, pllim commented on 09-Photutils/01-aperture_exercise_solution.py
> +f160w_zpt = 25.9447
```suggestion
f160w_zpt = 25.941
```

2025-01-06 18:35 UTC, pllim commented on 09-Photutils/04-segmentation_exercise2_solution.py
> +f160w_abmag = -2.5 * np.log10(f160w_tbl['segment_flux'].value) + 25.9447
```suggestion
f105w_abmag = -2.5 * np.log10(f105w_cat.segment_flux.value) + 26.266
f160w_abmag = -2.5 * np.log10(f160w_tbl['segment_flux'].value) + 25.941
```

2025-01-06 18:37 UTC, larrybradley approved these changes
@pllim LGTM, thanks!

2025-01-06 18:38 UTC, larrybradley commented
@pllim I don't have write permissions, so I cannot accept the suggestions or merge this PR.

2025-01-06 18:41 UTC, pllim commented
No worries, I can do it. Thanks for the review!

2025-01-06 18:48 UTC, pllim commented
Errr... I don't think the failures are related.

`2 notebooks raised unexpected errors while executing cells: ['Specutils_overview_solutions.ipynb', 'Specutils_overview.ipynb']`

2025-01-06 18:48 UTC, merged